name: "Podcast Generator"
author: "Snorlax"
description: "generate a file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs: 
  email: 
    description: the comiters email address
    required: true
    default: ${{ github.actor}}@localhost
  name:
    description: the commiter's name
    required: true
    default: ${{ github.actor }}
    